# appendix/prototype/prototype_schema.py

```python
"""
prototype_schema.py

Schema definition for LLM-assisted accounting preparation.

This module defines the expected structured output from an LLM when processing
receipts, invoices, payment records, or text memos.

This is not a tax decision engine.
This is not accounting software.
This is a Proof of Concept for the data structure described in the whitepaper:

"LLM時代の小規模事業運営モデル"
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, field_validator


class ConfirmationStatus(str, Enum):
    """Recommended confirmation status values."""

    CONFIRMED = "confirmed"
    NEEDS_REVIEW = "needs_review"
    EVIDENCE_MISSING = "evidence_missing"
    TAX_TYPE_NEEDS_REVIEW = "tax_type_needs_review"
    INVOICE_NEEDS_REVIEW = "invoice_needs_review"
    PAYER_NEEDS_REVIEW = "payer_needs_review"
    POSSIBLE_DUPLICATE = "possible_duplicate"
    PENDING = "pending"


class JournalEntryCandidate(BaseModel):
    """
    Structured journal-entry candidate generated from receipt evidence,
    OCR result, or user-provided transaction memo.

    The values generated by an LLM should be treated as candidates.
    Final accounting and tax decisions remain the user's responsibility.
    """

    date: str = Field(
        description="Transaction date shown on receipt or evidence. Format: YYYY-MM-DD."
    )
    vendor: str = Field(
        description="Vendor, store, service provider, or payee."
    )
    amount_tax_included: int = Field(
        ge=0,
        description="Total amount shown on the evidence, including tax."
    )
    payment_method: str = Field(
        description="Payment method, e.g. cash, bank transfer, corporate card, personal card, debit card."
    )
    payer: str = Field(
        description="Actual payer, e.g. company, representative, director, third party."
    )

    debit_account: str = Field(
        description="Candidate debit account."
    )
    debit_amount_tax_excluded: Optional[int] = Field(
        default=None,
        ge=0,
        description="Tax-excluded debit amount if separable."
    )
    tax_type: str = Field(
        description="Candidate tax classification, e.g. taxable purchase 10%, non-taxable, out of scope, needs review."
    )
    tax_amount: Optional[int] = Field(
        default=None,
        ge=0,
        description="Consumption tax amount shown or calculated."
    )

    credit_account: str = Field(
        description="Candidate credit account."
    )
    credit_amount: int = Field(
        ge=0,
        description="Credit-side amount, usually equal to total payment amount."
    )

    description: str = Field(
        description="Short bookkeeping description."
    )
    audit_log: str = Field(
        description="Explanation of business purpose, account reasoning, payment route, and unresolved issues."
    )

    evidence_type: str = Field(
        description="Evidence type, e.g. paper receipt, electronic invoice, card statement, bank record."
    )
    evidence_location: str = Field(
        description="File or folder location where the evidence is saved."
    )

    confirmation_status: ConfirmationStatus = Field(
        default=ConfirmationStatus.NEEDS_REVIEW,
        description="Confirmation status for this entry."
    )
    notes: str = Field(
        default="",
        description="Additional notes, warnings, assumptions, or unresolved issues."
    )

    @field_validator("date", "vendor", "debit_account", "credit_account", "description", "audit_log")
    @classmethod
    def required_text_must_not_be_empty(cls, value: str) -> str:
        """Reject empty strings for core textual fields."""
        if not value or not value.strip():
            raise ValueError("This field must not be empty.")
        return value.strip()

    def is_amount_balanced(self) -> bool:
        """
        Check whether debit side and credit side are numerically consistent.

        In this prototype, the intended structure is:

        debit_amount_tax_excluded + tax_amount == credit_amount

        If tax fields are missing, fall back to:

        amount_tax_included == credit_amount
        """
        if self.debit_amount_tax_excluded is not None and self.tax_amount is not None:
            return self.debit_amount_tax_excluded + self.tax_amount == self.credit_amount

        return self.amount_tax_included == self.credit_amount

    def needs_review(self) -> bool:
        """Return True if this entry should be reviewed before final use."""
        return self.confirmation_status != ConfirmationStatus.CONFIRMED


if __name__ == "__main__":
    sample = JournalEntryCandidate(
        date="2026-04-15",
        vendor="Example Electronics",
        amount_tax_included=55000,
        payment_method="Personal credit card",
        payer="Representative",
        debit_account="Supplies Expense",
        debit_amount_tax_excluded=50000,
        tax_type="Taxable purchase 10%",
        tax_amount=5000,
        credit_account="Officer Loan",
        credit_amount=55000,
        description="Business-use PC monitor purchase.",
        audit_log=(
            "The user states that the monitor is used for business development work. "
            "Payment was made by the representative's personal card, so the credit-side "
            "account is treated as an officer loan candidate. Final treatment should be reviewed."
        ),
        evidence_type="Paper receipt",
        evidence_location="2026_FiscalYear/04/01_original/",
        confirmation_status=ConfirmationStatus.CONFIRMED,
        notes="Sample entry."
    )

    print(sample.model_dump_json(indent=2, ensure_ascii=False))
    print("balanced:", sample.is_amount_balanced())
```
